// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siduunqslodnwxwqezzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZHV1bnFzbG9kbnd4d3Flenp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NDk3OTYsImV4cCI6MjA1NDMyNTc5Nn0.uPWLC1_ZigtCktofiL6751xJWrKqe5nBNTWiih2FNz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);